CREATE SCHEMA TAKEAWAY_SHOP;

CREATE TABLE TAKEAWAY_SHOP.STAFF (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  max_weekly_hours INT NOT NULL
);

CREATE TABLE TAKEAWAY_SHOP.ROLES (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  description VARCHAR(255) NOT NULL,
);

CREATE TABLE TAKEAWAY_SHOP.SHIFTS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  day ENUM('MON','TUE','WED','THU','FRI','SAT','SUN') NOT NULL,
  hours INT NOT NULL,
  req_role BIGINT NOT NULL,
  assignee BIGINT,
);

CREATE TABLE TAKEAWAY_SHOP.STAFF_ROLES (
  id_employee BIGINT NOT NULL,
  id_role BIGINT NOT NULL,
);

CREATE TABLE TAKEAWAY_SHOP.STAFF_UNAVAILABILITY (
  id_employee BIGINT NOT NULL,
  day ENUM('MON','TUE','WED','THU','FRI','SAT','SUN') NOT NULL,
);

ALTER TABLE TAKEAWAY_SHOP.SHIFTS
ADD FOREIGN KEY (req_role)
REFERENCES TAKEAWAY_SHOP.ROLES(id);

ALTER TABLE TAKEAWAY_SHOP.SHIFTS
ADD FOREIGN KEY (assignee)
REFERENCES TAKEAWAY_SHOP.STAFF(id);

ALTER TABLE TAKEAWAY_SHOP.STAFF_UNAVAILABILITY
ADD FOREIGN KEY (id_employee)
REFERENCES TAKEAWAY_SHOP.STAFF(id);

INSERT INTO TAKEAWAY_SHOP.ROLES (description)
VALUES ('Chef'), ('Cook'), ('Dishwasher'), ('Manager'), ('Baristo');

INSERT INTO TAKEAWAY_SHOP.STAFF (max_weekly_hours)
VALUES (40), (30), (30), (30), (30), (30), (30), (30), (30), (30), (30), (30), (40);

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 9, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Manager'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 8, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 4, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 7, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 3, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SAT', 8, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 9, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Manager'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 8, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 6, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 8, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 4, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 5, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher'));

INSERT INTO TAKEAWAY_SHOP.SHIFTS (day, hours, req_role)
VALUES ('SUN', 5, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher'));

INSERT INTO TAKEAWAY_SHOP.STAFF_ROLES (id_employee, id_role)
VALUES  (1, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Manager')),
        (1, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (2, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (2, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook')),
        (3, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher')),
        (4, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (5, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (6, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook')),
        (7, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher')),
        (8, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Manager')),
        (9, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (10, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook')),
        (11, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Cook')),
        (12, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Chef')),
        (13, (select id from TAKEAWAY_SHOP.ROLES where ROLES.description = 'Dishwasher'));

INSERT INTO TAKEAWAY_SHOP.STAFF_UNAVAILABILITY (id_employee, day)
VALUES (1, 'MON'), (4, 'THU'), (4, 'FRI'), (8, 'SUN'), (9, 'TUE'), (9, 'WED');
